version: '3.3'

services:
   fvtt:
      build:
        context: ./image
        dockerfile: ./Dockerfile
        args:
            UID: 1026
            GUID: 65534
      image: fvtt:latest            
      container_name: foundryvtt
      volumes:
        - ./nginx:/etc/nginx/sites-enabled
        - ./cron.d:/etc/cron.d
        - ./supervisor:/etc/supervisor/conf.d
        - ./letsencrypt/etc:/etc/letsencrypt
        - ./letsencrypt/var/lib:/var/lib/letsencrypt
        - ./letsencrypt/data:/data/letsencrypt
        - ./data:/var/foundry/data
        - ./log:/var/log
      ports:
        - "80:80"
        - "443:443"
      restart: always